// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Money_CLI;

#nullable disable

namespace Money_CLI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230113202531_MinorModification")]
    partial class MinorModification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Money_CLI.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("Amount");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date_in");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Day");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Month");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Money_CLI.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("Amount");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date_in");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Day");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Month");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
